### ISSUE TITLE
Tracking: Add basic donation support to flathub frontend

### ISSUE THREAD

**Issue by danielsilverstone-ct** [flathub/frontend#238]
To support the basic donation support outlined in backend#138 we need the following frontend work doing:

* [ ] Add basic wallet (cards) and transactions/orders page to user info
* [ ] Support retrieving keys and constructing Stripe objects lazily
* [ ] Add flow for completing a `new` or `retry` status transaction
* [ ] Come up with a basic "Make a donation to Flathub" UI
* [ ] Deploy this to beta
